# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "devserver"
  config.vm.network :private_network, ip: '192.168.42.42'
  config.vm.hostname = 'base.dev'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.provision :puppet do |pup|
    pup.manifests_path = "manifests"
    pup.manifest_file = "default.pp"
    pup.module_path = "modules"
  end
end
